sonar.projectKey=andresmendoza59_celular-pro-api
sonar.organization=andresmendoza59


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=celular-pro-api
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=./coverage/coverage-final.json

name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npm run test -- --coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}


